"""tournament round beat stamps + thread index

Revision ID: 178e45a74fa8
Revises: d58b9d2d161a
Create Date: 2026-09-03 11:02:45.317158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178e45a74fa8'
down_revision: Union[str, Sequence[str], None] = 'd58b9d2d161a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tournament_matches_thread', 'tournament_matches', ['thread_id'], unique=False)
    op.add_column('tournament_rounds', sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournament_rounds', sa.Column('resulted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_rounds', 'resulted_at')
    op.drop_column('tournament_rounds', 'revealed_at')
    op.drop_index('ix_tournament_matches_thread', table_name='tournament_matches')
    # ### end Alembic commands ###
