"""play score clear override

Revision ID: 1acd77155bd9
Revises: b58a8e2b2185
Create Date: 2026-08-31 15:44:48.359166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acd77155bd9'
down_revision: Union[str, Sequence[str], None] = 'b58a8e2b2185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_scores', sa.Column('clear_override', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_scores', 'clear_override')
    # ### end Alembic commands ###
