"""pending_requests durable approvals

Revision ID: 1c69109e03f1
Revises: 448eeff195d4
Create Date: 2026-07-18 01:42:32.561390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c69109e03f1'
down_revision: Union[str, Sequence[str], None] = '448eeff195d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'expired', 'cancelled', name='request_status'), server_default='pending', nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('responder_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dm_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('dm_message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_requests_lookup', 'pending_requests', ['kind', 'responder_id', 'status'], unique=False)
    op.create_index('ix_pending_requests_sweep', 'pending_requests', ['status', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_pending_requests_sweep', table_name='pending_requests')
    op.drop_index('ix_pending_requests_lookup', table_name='pending_requests')
    op.drop_table('pending_requests')
    # create_table auto-created the enum type; drop_table does not, so do it here.
    sa.Enum(name='request_status').drop(op.get_bind(), checkfirst=True)
