"""per-difficulty artist/charter links

Revision ID: 1d8a799695c9
Revises: 66ad9752c1d2
Create Date: 2026-05-24 17:03:47.211856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8a799695c9'
down_revision: Union[str, Sequence[str], None] = '66ad9752c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty_artists',
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['difficulty_id'], ['song_difficulties.id'], ),
    sa.PrimaryKeyConstraint('difficulty_id', 'artist_id')
    )
    op.create_table('difficulty_charters',
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('charter_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['charter_id'], ['charters.charter_id'], ),
    sa.ForeignKeyConstraint(['difficulty_id'], ['song_difficulties.id'], ),
    sa.PrimaryKeyConstraint('difficulty_id', 'charter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('difficulty_charters')
    op.drop_table('difficulty_artists')
    # ### end Alembic commands ###
