"""one account per discord: unique(discord_id), drop is_primary, play_scores FK RESTRICT

Revision ID: 460bea66bb35
Revises: a878e80ad898
Create Date: 2026-07-18 09:28:19.940069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460bea66bb35'
down_revision: Union[str, Sequence[str], None] = 'a878e80ad898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('play_scores_arcaea_account_id_fkey'), 'play_scores', type_='foreignkey')
    op.create_foreign_key('play_scores_arcaea_account_id_fkey', 'play_scores', 'arcaea_accounts', ['arcaea_account_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('player_links_discord_id_arcaea_account_id_key'), 'player_links', type_='unique')
    op.create_unique_constraint('uq_player_links_discord_id', 'player_links', ['discord_id'])
    op.drop_column('player_links', 'is_primary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_links', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_player_links_discord_id', 'player_links', type_='unique')
    op.create_unique_constraint(op.f('player_links_discord_id_arcaea_account_id_key'), 'player_links', ['discord_id', 'arcaea_account_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('play_scores_arcaea_account_id_fkey', 'play_scores', type_='foreignkey')
    op.create_foreign_key(op.f('play_scores_arcaea_account_id_fkey'), 'play_scores', 'arcaea_accounts', ['arcaea_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
