"""chart link override flags

Revision ID: 4d84f2bf5710
Revises: 1d8a799695c9
Create Date: 2026-05-24 17:14:59.999452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d84f2bf5710'
down_revision: Union[str, Sequence[str], None] = '1d8a799695c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_difficulties', sa.Column('artists_overridden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('song_difficulties', sa.Column('charters_overridden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_difficulties', 'charters_overridden')
    op.drop_column('song_difficulties', 'artists_overridden')
    # ### end Alembic commands ###
