"""owned charts

Revision ID: 672b47e418d3
Revises: d7b2f4c19e83
Create Date: 2026-09-06 23:29:58.771780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672b47e418d3'
down_revision: Union[str, Sequence[str], None] = 'd7b2f4c19e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_charts',
    sa.Column('arcaea_account_id', sa.Integer(), nullable=False),
    sa.Column('song_difficulty_id', sa.Integer(), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arcaea_account_id'], ['arcaea_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_difficulty_id'], ['song_difficulties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('arcaea_account_id', 'song_difficulty_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_charts')
    # ### end Alembic commands ###
