"""chardle channel and player threads

Revision ID: 705ec00fbbd8
Revises: a97f24335635
Create Date: 2026-07-27 17:16:40.812351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705ec00fbbd8'
down_revision: Union[str, Sequence[str], None] = 'a97f24335635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chardle_channels',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('scoreboard_message_id', sa.BigInteger(), nullable=True),
    sa.Column('scoreboard_puzzle_number', sa.Integer(), nullable=True),
    sa.Column('set_by', sa.BigInteger(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('chardle_player_threads',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'discord_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chardle_player_threads')
    op.drop_table('chardle_channels')
    # ### end Alembic commands ###
