"""play_scores

Revision ID: 72cf0122181a
Revises: bb134e0345ba
Create Date: 2026-07-18 01:25:43.405482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cf0122181a'
down_revision: Union[str, Sequence[str], None] = 'bb134e0345ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arcaea_account_id', sa.Integer(), nullable=False),
    sa.Column('wire_song_id', sa.String(), nullable=False),
    sa.Column('wire_difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time_played', sa.BigInteger(), nullable=False),
    sa.Column('song_difficulty_id', sa.Integer(), nullable=True),
    sa.Column('shiny_pure_count', sa.Integer(), nullable=True),
    sa.Column('pure_count', sa.Integer(), nullable=True),
    sa.Column('far_count', sa.Integer(), nullable=True),
    sa.Column('lost_count', sa.Integer(), nullable=True),
    sa.Column('health', sa.SmallInteger(), nullable=True),
    sa.Column('clear_type', sa.Enum('track_lost', 'clear', 'full_recall', 'pure_memory', 'easy_clear', 'hard_clear', name='clear_type'), nullable=True),
    sa.Column('modifier', sa.Enum('normal', 'easy', 'hard', name='gauge_modifier'), nullable=True),
    sa.Column('wire_play_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arcaea_account_id'], ['arcaea_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_difficulty_id'], ['song_difficulties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arcaea_account_id', 'wire_song_id', 'wire_difficulty', 'score', 'time_played', name='uq_play_identity')
    )
    op.create_index('ix_play_scores_account_chart_score', 'play_scores', ['arcaea_account_id', 'song_difficulty_id', 'score'], unique=False)
    op.create_index('ix_play_scores_account_time', 'play_scores', ['arcaea_account_id', 'time_played'], unique=False)
    op.create_index('uq_play_scores_wire_play_id', 'play_scores', ['wire_play_id'], unique=True, postgresql_where='wire_play_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_play_scores_wire_play_id', table_name='play_scores', postgresql_where='wire_play_id IS NOT NULL')
    op.drop_index('ix_play_scores_account_time', table_name='play_scores')
    op.drop_index('ix_play_scores_account_chart_score', table_name='play_scores')
    op.drop_table('play_scores')
    # create_table auto-created these pg enum types; drop_table does not remove
    # them, so a re-upgrade would fail on "type already exists" without this.
    sa.Enum(name='clear_type').drop(op.get_bind())
    sa.Enum(name='gauge_modifier').drop(op.get_bind())
    # ### end Alembic commands ###
