"""artist kind and unit membership

Revision ID: 9a4cb65d96c8
Revises: b3f1c2d4e5a6
Create Date: 2026-05-25 12:17:16.438007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4cb65d96c8'
down_revision: Union[str, Sequence[str], None] = 'b3f1c2d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_members',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['artists.artist_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['artists.artist_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    # add_column does not auto-create the enum type (unlike create_table); do it explicitly.
    artist_kind = sa.Enum('person', 'unit', name='artist_kind')
    artist_kind.create(op.get_bind(), checkfirst=True)
    op.add_column('artists', sa.Column('kind', artist_kind, server_default='person', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'kind')
    op.drop_table('artist_members')
    # ### end Alembic commands ###
    sa.Enum(name='artist_kind').drop(op.get_bind(), checkfirst=True)
