"""spoiler versions

Revision ID: 9fbd1bd80128
Revises: f1a2b3c4d5e6
Create Date: 2026-08-27 11:15:54.983163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbd1bd80128'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spoiler_versions',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('set_by', sa.BigInteger(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spoiler_versions')
    # ### end Alembic commands ###
