"""browser_identity on bot_accounts and player_credentials

Revision ID: a878e80ad898
Revises: 1c69109e03f1
Create Date: 2026-07-18 08:07:54.498395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a878e80ad898'
down_revision: Union[str, Sequence[str], None] = '1c69109e03f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_accounts', sa.Column('browser_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('player_credentials', sa.Column('browser_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_credentials', 'browser_identity')
    op.drop_column('bot_accounts', 'browser_identity')
    # ### end Alembic commands ###
