"""chardle puzzles sessions guesses

Revision ID: a97f24335635
Revises: 7ac31e9b0d54
Create Date: 2026-07-27 16:09:31.317655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a97f24335635'
down_revision: Union[str, Sequence[str], None] = '7ac31e9b0d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chardle_puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_difficulty_id', sa.Integer(), nullable=False),
    sa.Column('clue_columns', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=True),
    sa.Column('puzzle_number', sa.Integer(), nullable=True),
    sa.Column('is_daily', sa.Boolean(), sa.Computed('puzzle_number IS NOT NULL', persisted=True), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('puzzle_number IS NULL OR filters IS NULL', name='ck_chardle_puzzles_daily_unfiltered'),
    sa.ForeignKeyConstraint(['song_difficulty_id'], ['song_difficulties.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'is_daily', name='uq_chardle_puzzles_id_daily'),
    sa.UniqueConstraint('puzzle_number')
    )
    op.create_table('chardle_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('board_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Enum('playing', 'won', 'lost', name='chardle_state'), server_default='playing', nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(discord_id IS NOT NULL) = is_daily AND (channel_id IS NOT NULL) = (NOT is_daily)', name='ck_chardle_sessions_owner'),
    sa.CheckConstraint('channel_id IS NULL OR channel_id = board_channel_id', name='ck_chardle_sessions_board_in_owner'),
    sa.ForeignKeyConstraint(['puzzle_id', 'is_daily'], ['chardle_puzzles.id', 'chardle_puzzles.is_daily'], name='fk_chardle_sessions_puzzle', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_id', 'discord_id', name='uq_chardle_sessions_daily_player')
    )
    op.create_index('ix_chardle_sessions_board', 'chardle_sessions', ['board_channel_id', 'message_id'], unique=False)
    op.create_index('ix_chardle_sessions_player', 'chardle_sessions', ['discord_id', 'state'], unique=False)
    op.create_index('uq_chardle_sessions_channel_live', 'chardle_sessions', ['channel_id'], unique=True, postgresql_where=sa.text("state = 'playing'"))
    op.create_table('chardle_guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('song_difficulty_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chardle_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_difficulty_id'], ['song_difficulties.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_chardle_guesses_ordinal'),
    sa.UniqueConstraint('session_id', 'song_difficulty_id', name='uq_chardle_guesses_chart')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chardle_guesses')
    op.drop_index('uq_chardle_sessions_channel_live', table_name='chardle_sessions', postgresql_where=sa.text("state = 'playing'"))
    op.drop_index('ix_chardle_sessions_player', table_name='chardle_sessions')
    op.drop_index('ix_chardle_sessions_board', table_name='chardle_sessions')
    op.drop_table('chardle_sessions')
    op.drop_table('chardle_puzzles')
    # ### end Alembic commands ###
    # create_table auto-created the enum type; drop_table does not, so do it here.
    sa.Enum(name='chardle_state').drop(op.get_bind(), checkfirst=True)
