"""beyond alt appearance flag

Revision ID: b58a8e2b2185
Revises: 9fbd1bd80128
Create Date: 2026-08-28 09:08:44.902927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58a8e2b2185'
down_revision: Union[str, Sequence[str], None] = '9fbd1bd80128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every Beyond shipped in 7.0 got the "Inscribed" reskin -- backfill them so the
# flag matches the game on day one instead of starting every chart plain.
_V7_BEYONDS = ('dreadarea', 'rivenpilgrim', 'deinosphainein', 'cataclysmcry')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_difficulties', sa.Column('alt', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            "UPDATE song_difficulties SET alt = true "
            "WHERE difficulty = 'byd' AND song_id = ANY(:song_ids)"
        ).bindparams(song_ids=list(_V7_BEYONDS))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_difficulties', 'alt')
    # ### end Alembic commands ###
