"""arcaea accounts, bot sessions, live updates

Revision ID: bb134e0345ba
Revises: c2e2341dbb6c
Create Date: 2026-07-17 16:31:03.194824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb134e0345ba'
down_revision: Union[str, Sequence[str], None] = 'c2e2341dbb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_enc', sa.String(), nullable=False),
    sa.Column('friend_code', sa.String(length=9), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('friend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_friends', sa.Integer(), server_default='10', nullable=False),
    sa.Column('cookie_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('friend_code')
    )
    op.create_table('live_update_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id')
    )
    op.create_table('live_update_prefs',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('arcaea_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_user_id', sa.Integer(), nullable=False),
    sa.Column('friend_code', sa.String(length=9), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bot_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_account_id'], ['bot_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arc_user_id'),
    sa.UniqueConstraint('friend_code')
    )
    op.create_table('player_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arcaea_account_id', sa.Integer(), nullable=False),
    sa.Column('email_enc', sa.String(), nullable=False),
    sa.Column('password_enc', sa.String(), nullable=False),
    sa.Column('cookie_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arcaea_online_expire_ts', sa.BigInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arcaea_account_id'], ['arcaea_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arcaea_account_id')
    )
    op.create_table('player_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('arcaea_account_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['arcaea_account_id'], ['arcaea_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id', 'arcaea_account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_links')
    op.drop_table('player_credentials')
    op.drop_table('arcaea_accounts')
    op.drop_table('live_update_prefs')
    op.drop_table('live_update_channels')
    op.drop_table('bot_accounts')
    # ### end Alembic commands ###
