"""config_values

Revision ID: c2e2341dbb6c
Revises: e2d7b8d4d77f
Create Date: 2026-06-06 10:24:25.259710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e2341dbb6c'
down_revision: Union[str, Sequence[str], None] = 'e2d7b8d4d77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_values',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('set_by', sa.BigInteger(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'scope', 'scope_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_values')
    # ### end Alembic commands ###
