"""tag category color

Revision ID: e2d7b8d4d77f
Revises: 9a4cb65d96c8
Create Date: 2026-05-26 16:04:19.075823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d7b8d4d77f'
down_revision: Union[str, Sequence[str], None] = '9a4cb65d96c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_categories', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_categories', 'color')
    # ### end Alembic commands ###
