"""tournament participant discord display name

Revision ID: e481b588edab
Revises: 178e45a74fa8
Create Date: 2026-09-03 11:23:14.987717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e481b588edab'
down_revision: Union[str, Sequence[str], None] = '178e45a74fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('display_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_participants', 'display_name')
    # ### end Alembic commands ###
