"""initial catalog schema

Revision ID: efbbe73d0c06
Revises: 
Create Date: 2026-05-23 21:14:32.208471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbbe73d0c06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('charters',
    sa.Column('charter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('charter_id')
    )
    op.create_table('packs',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_art', sa.String(), nullable=True),
    sa.Column('release_date', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('pack_id')
    )
    op.create_table('artist_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'alias')
    )
    op.create_table('charter_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charter_id', sa.String(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['charter_id'], ['charters.charter_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charter_id', 'alias')
    )
    op.create_table('songs',
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=True),
    sa.Column('pack_name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_jp', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('bpm', sa.String(), nullable=False),
    sa.Column('bpm_base', sa.Float(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('side', sa.SmallInteger(), nullable=False),
    sa.Column('world_unlock', sa.Boolean(), nullable=False),
    sa.Column('remote_download', sa.Boolean(), nullable=False),
    sa.Column('bg', sa.String(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('jacket', sa.String(), nullable=False),
    sa.Column('jacket_designer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.pack_id'], ),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('idx')
    )
    op.create_table('song_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'alias')
    )
    op.create_table('song_artists',
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'artist_id')
    )
    op.create_table('song_charters',
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('charter_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['charter_id'], ['charters.charter_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('song_id', 'charter_id')
    )
    op.create_table('song_difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Enum('pst', 'prs', 'ftr', 'byd', 'etr', 'byd_2', 'err', name='difficulty_class'), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('chart_designer', sa.String(), nullable=True),
    sa.Column('game_song_id', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('bpm', sa.String(), nullable=True),
    sa.Column('bpm_base', sa.Float(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('side', sa.SmallInteger(), nullable=True),
    sa.Column('world_unlock', sa.Boolean(), nullable=True),
    sa.Column('remote_download', sa.Boolean(), nullable=True),
    sa.Column('bg', sa.String(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('jacket', sa.String(), nullable=True),
    sa.Column('jacket_designer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'difficulty')
    )
    op.create_table('difficulty_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['song_difficulties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('difficulty_id', 'alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('difficulty_aliases')
    op.drop_table('song_difficulties')
    op.drop_table('song_charters')
    op.drop_table('song_artists')
    op.drop_table('song_aliases')
    op.drop_table('songs')
    op.drop_table('charter_aliases')
    op.drop_table('artist_aliases')
    op.drop_table('packs')
    op.drop_table('charters')
    op.drop_table('artists')
    # ### end Alembic commands ###
    # create_table auto-created this enum type; drop it so upgrade re-runs cleanly.
    sa.Enum(name='difficulty_class').drop(op.get_bind(), checkfirst=True)
