"""account tracking flag

Revision ID: fba7cd1057fe
Revises: d3f9a1c07b2e
Create Date: 2026-07-22 09:42:19.400270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba7cd1057fe'
down_revision: Union[str, Sequence[str], None] = 'd3f9a1c07b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arcaea_accounts', sa.Column('tracking_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arcaea_accounts', 'tracking_enabled')
    # ### end Alembic commands ###
